casino_games:
  path: /games/casino
  controller: 'App\Controller\Games\CasinoGamesController::index'
index:
  path: /
  controller: 'App\Controller\HomeController::index'
load_games_by_category:
  path: /games/casino/loadGamesByCategory/{categoryId}
  controller: 'App\Controller\Games\CasinoGamesController::loadGamesByCategory'
search_games_by_name:
  path: /games/casino/search
  controller: 'App\Controller\Games\CasinoGamesController::searchGames'
all_casino_games:
  path: /games/casino/all
  controller: 'App\Controller\Games\CasinoGamesController::getAllGames'
load_games_by_provider:
  path: /games/casino/loadGamesByProvider/{provider}
  controller: 'App\Controller\Games\CasinoGamesController::loadGamesByProvider'
games_filtered_by_category:
  path: /games/casino/gamesFilteredByCategory
  controller: 'App\Controller\Games\CasinoGamesController::loadAllGamesByCategory'
play_casino_game:
  path: "/games/casino/{id}"
  controller: 'App\Controller\Games\CasinoGamesController::gameDetails'
  requirements:
  methods: ["GET"]
not_found:
  path: /{url}
  controller: App\Controller\DefaultController::notFound
  requirements:
    url: .+
